# .streamlit/secrets.toml

sender_email = st.secrets["EMAIL"]
app_password = st.secrets["APP_PASSWORD"]


ONEDRIVE_URL1 =   # anonymous link
ONEDRIVE_URL2 = 


[urls]
live_urls = [ "https://1drv.ms/x/c/d6aca2526f83594b/IQAMcIopdLU9SINiVRsgBHwWAZsXQJ5-PHSv1BevGvZ8f0Q?download=1",
              "https://1drv.ms/x/c/d6aca2526f83594b/IQAlE6FfCDS_QL0HXfdxWdtCAae3Ilx-a_K9hA_PXGN3Ofs?download=1"
               ]


